name: diagrams
description: An app that let you draw diagrams.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: 1.1.0
  flutter_bloc: 8.0.1
  bloc_test: ^9.0.3
  get_it: 7.2.0
  golden_toolkit: 0.13.0
  file_selector: 0.8.4+1
  equatable: 2.0.3
  json_annotation: 4.4.0
  json_serializable: 6.1.5
  package_info_plus: 1.4.0
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
  mockito: ^5.1.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size 
  # system_tray: ^0.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: 2.1.7
  freezed: 1.1.0

flutter:
  uses-material-design: true
