# Name of your workflow.
name: flutter tests
# Trigger the workflow on push or pull request.
on: [push, pull_request]
# A workflow run is made up of one or more jobs.
jobs:
  # id of job, a string that is unique to the "jobs" node above.
  build:
    # The type of machine to run the job on.
    runs-on: macOS-latest
    # Contains a sequence of tasks.
    steps:
    # The branch or tag ref that triggered the workflow will be 
    # checked out.
    # https://github.com/actions/checkout
    - uses: actions/checkout@v2
    # Sets up a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'dev' or 'beta'
        flutter-version: '2.10.3'
    - name: Install dependencies
      run: flutter pub get
    - name: Run Flutter tests
      run: flutter test test/main_test.dart